sync interface with api
OrteliusAB/inorigojs pull request #19
Opened 2022-02-22 09:43 UTC by orteliusortdsg

Added interfaces API:

- ModuleAPI
- FavoritesAPI
- ThemeAPI
- MiscellaneousAPI

And new functions added in:

- KnowledgeSetAPI
- EntityAPI
- VersoRuntimeAPI (Application)
- ResourceAPI

**ThemeAPI**
applyTheme()
getWorkbenchStylesheet()
getWorkbenchTheme()
getTheme()
getThemedImage()
getImage()
getCss()
getVariables()
getVariablesSession()
getCssSession()
getCssPortal()
getVariablesPortal()
getVariablesDefault()
getCssDefault()

**VersoRuntimeAPI (Application)** 
triggerAction()
setComponentEnabled()
setComponentReadOnly()
setComponentVisible()

**ModuleAPI**
registerModule()
getModule()
deleteModule()
deleteDependency() 
registerDependency()

**ResourceAPI**
getResourceData()

**FavoriteAPI**
deleteFavorite()
createFavorite()
getFavorites()
getFavorite()

**MiscellaneousAPI** 
getUser()
excecute()
registerActivity() 
getDynamicImage() 
getRelationDirectionIcon() 
getRelationIcon()

**EntityAPI**
generateID()
getEntityGranted()

**KnowledgeSetAPI**
searchResultAsObjects()
getResultAsObjects() 
exportToFile()

2022-03-21 12:36 UTC, orteliusorthon requested changes

2022-03-21 12:36 UTC, orteliusorthon commented on docs/docs/documentation/inorigoapi.md
> +const coreAPI = api.getModuleAPI()
Borde det inte bli const moduleAPI = x ?

2022-03-21 12:36 UTC, orteliusorthon commented on docs/docs/documentation/inorigoapi.md
> +const coreAPI = api.getFavoriteAPI()
Borde det inte bli const FavoriteAPI = x ?

2022-03-21 12:36 UTC, orteliusorthon commented on docs/docs/documentation/inorigoapi.md
> +const coreAPI = api.getMiscellaneousAPI()
Borde det inte bli MiscAPI = x ?

Osvosv..

2022-03-21 12:36 UTC, orteliusorthon commented on src/API/MiscellaneousAPI.js
> +	 * @param {object} requestBody -  Bode example: {"activityID": 0, "activity": "string", "eventType": "string", "userID": "string", "targetID": { "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "dataTy
Man kan beskriva en payload i param-klamrarna genom typescript syntax.
T.ex:
\@param {{ activityID: number, activity: string, eventType: string, userID: string, targetID: { id: "string", dataType: string }, details: string }} requestBody - Request Payload
Då får man Intellisense-stöd (som autocomplete osv) i VSC när man använder biblioteket.

2022-04-19 07:41 UTC, orteliusortdsg commented on docs/docs/documentation/inorigoapi.md
> +const coreAPI = api.getModuleAPI()
Ändrad

2022-04-19 07:42 UTC, orteliusortdsg commented on docs/docs/documentation/inorigoapi.md
> +const coreAPI = api.getFavoriteAPI()
Ändrad

2022-04-19 07:42 UTC, orteliusortdsg commented on docs/docs/documentation/inorigoapi.md
> +const coreAPI = api.getMiscellaneousAPI()
Ändrad

2022-04-19 07:43 UTC, orteliusortdsg commented on src/API/MiscellaneousAPI.js
> +	 * @param {object} requestBody -  Bode example: {"activityID": 0, "activity": "string", "eventType": "string", "userID": "string", "targetID": { "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "dataTy
Har lagt beskrivning av payload i param-klamrarna.

2022-04-19 07:45 UTC, orteliusortdsg commented on src/API/KnowledgeSetAPI.js
> +		this.parentAPI.setDefaultRequestHeader("Accept", mediaType)
Har ändrat så aktuella header konfiguration görs lokalt i funktionerna där de behövs

2022-08-17 08:07 UTC, closed without merging

2022-08-17 08:08 UTC, orteliusortdsg commented
Not current branch